{% set name = "emmet-api" %}
{% set version = "0.38.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emmet-api-{{ version }}.tar.gz
  sha256: 2409f403ce3e212bff3df667f591f6740eec3e7f9f4073938cb56aa980aa5e89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - fastapi
    - gunicorn
    - maggma
    - python >={{ python_min }}
    - uvicorn
    - pydantic <2.10

test:
  imports:
    - emmet.api
    - emmet.api.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/emmet
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
