{% set name = "emmet-api" %}
{% set version = "0.38.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-api-{{ version }}.tar.gz
  sha256: ce0da317e708ad113aab66f8ca67bb28a67e06ff5b9e2463b9e854551725737c
  patches:
    - pypi.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - fastapi
    - gunicorn
    - maggma
    - python >=3.8
    - uvicorn

test:
  imports:
    - emmet.api
    - emmet.api.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
