{% set name = "emmet-api" %}
{% set version = "0.38.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-api-{{ version }}.tar.gz
  sha256: b9a2302454972fcbc256214b173af21ed6b289f3af803debf912bf2f4af48dec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - pydantic-core <2
    - fastapi
    - gunicorn
    - maggma
    - python >=3.8
    - uvicorn

test:
  imports:
    - emmet.api
    - emmet.api.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
