{% set name = "emmet-api" %}
{% set version = "0.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/emmet/archive/v{{ version }}.tar.gz
  sha256: 96faa008b25fbb7777fd28cdf0703b8b2af8153a1b7b7099e76f67e09c88a5a9

build:
  noarch: python
  script: cd emmet-api && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - fastapi
    - gunicorn
    - maggma
    - python >=3.8
    - uvicorn

test:
  imports:
    - emmet.api
    - emmet.api.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
