schema_version: 1

context:
  name: emmet-api
  version: "0.87.3"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 543ba8d891b81c99e1d72afccdf3497216080cd08dc59d75f3b3e91fc53f1be3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - fastapi
    - gunicorn
    - maggma
    - python >=${{ python_min }}
    - uvicorn
    - pydantic
    - asgi-logger
    - ddtrace
    - shapely
    - setproctitle
    - pymatgen-analysis-alloys
    - pymatgen-analysis-defects

tests:
  - python:
      imports:
        - emmet.api
        - emmet.api.core
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsproject/emmet

extra:
  recipe-maintainers:
    - jan-janssen
