schema_version: 1

context:
  name: emmet-api
  version: "0.87.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 0448c9ea49f993f5cc69a587b7b8b51cd700a9cf1687214022e9f94ae66ce2ff

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python 3.11.*
    - setuptools
    - setuptools-scm
  run:
    - boto3
    - emmet-core
    - fastapi
    - gunicorn
    - maggma
    - python >=${{ python_min }}
    - uvicorn
    - pydantic
    - asgi-logger
    - ddtrace
    - shapely
    - setproctitle
    - pymatgen-analysis-alloys
    - pymatgen-analysis-defects

tests:
  - python:
      imports:
        - emmet.api
        - emmet.api.core
      pip_check: false
      python_version: ${{ python_min }}
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:

about:
  summary: Emmet API Library
  license: BSD-3-Clause
  license_file:
    - LICENSE
  homepage: https://github.com/materialsproject/emmet

extra:
  recipe-maintainers:
    - jan-janssen
